name: Terraform Validations

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'feature/*'

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write    

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.8.2

jobs:
  validations:
    name: Terraform Validations and Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf*') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Run Terraform FMT
        run: terraform fmt -check -recursive -diff

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Run Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          mkdir -p test-reports
          tflint --format=junit --recursive --chdir= > test-reports/tflint-report.xml || true

      - name: Upload TfLint Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tf-lint-report
          path: test-reports/tflint-report.xml

      - name: Setup Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          export PATH=$PATH:$(pwd)/bin
          trivy config ./ -f template --template "@contrib/junit.tpl" --severity HIGH,CRITICAL --output test-reports/trivy-report.xml || true

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: triy-report
          path: test-reports/trivy-report.xml

  publish:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: validations  # Publish after validations job completes
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v3
        with:
          name: validation-reports

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # Always run even if the validations job fails
        with:
          files: |
            test-reports/tflint-report.xml
            test-reports/trivy-report.xml
