name: Lint
on:
    push:
      branches:
        - 'feature/*'  # Trigger workflow only on feature branches
    pull_request:
      branches:
        - 'feature/*'  # Trigger workflow on pull requests to feature branches

jobs:
  tflint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-v0.52.0-${{ hashFiles('.tflint.hcl') }}
        restore-keys: |
          ${{ matrix.os }}-tflint-

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.52.0

    - name: Show TFLint version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Avoid rate limiting

    - name: Create test-reports directory
      run: mkdir -p test-reports

    - name: Run TFLint on multiple directories
      run: |
        for dir in ./iam ./resources; do
          tflint --format junit --chdir="$dir" >> test-reports/tflint-report.xml || true
        done
