name: Trivy IaC Scan

on:
  push:
    branches:
      - 'feature/*'  # Trigger workflow only on feature branches
  pull_request:
    branches:
      - 'feature/*'  # Trigger workflow on pull requests to feature branches

jobs:
  build:
    name: Trivy IaC Scan
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'  # Scan for misconfigurations in IaC
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'  # Fail the build if vulnerabilities are found
          ignore-unfixed: true  # Ignore issues with no fix available
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
